repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
    -   id: check-merge-conflict # Check for files that contain merge conflict strings.
    -   id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
    -   id: requirements-txt-fixer # Sorts entries in requirements.txt
    -   id: forbid-new-submodules # Check for git submodules
    -   id: flake8 # runs python flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        exclude: tests
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: venv/bin/pytest
        language: script
        pass_filenames: false
        always_run: true
-   repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    -   id: black
        language_version: python3 # Should be a command that runs python3.6+
